language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
script: "nosetests --with-coverage linie tests/"
after_success:
  - coveralls
